// @routes-hash d720e722c75923fb1d500ea491cf7c73
import { Express } from "express";

import route1 from "./routes/assets/addAssets";
import route2 from "./routes/assets/delAssets";
import route3 from "./routes/assets/delAssetsImage";
import route4 from "./routes/assets/generateAssets";
import route5 from "./routes/assets/getAssets";
import route6 from "./routes/assets/getImage";
import route7 from "./routes/assets/getStoryboard";
import route8 from "./routes/assets/polishPrompt";
import route9 from "./routes/assets/saveAssets";
import route10 from "./routes/assets/updateAssets";
import route11 from "./routes/batch/cancelBatchTask";
import route12 from "./routes/batch/createBatchTask";
import route13 from "./routes/batch/getBatchTaskStatus";
import route14 from "./routes/costume/addCostume";
import route15 from "./routes/costume/checkConsistency";
import route16 from "./routes/costume/deleteCostume";
import route17 from "./routes/costume/generateCostume";
import route18 from "./routes/costume/getCostumes";
import route19 from "./routes/costume/updateCostume";
import route20 from "./routes/format/convertFormat";
import route21 from "./routes/format/detectFormat";
import route22 from "./routes/format/parseFormat";
import route23 from "./routes/index/index";
import route24 from "./routes/monitoring/health";
import route25 from "./routes/monitoring/metrics";
import route26 from "./routes/novel/addNovel";
import route27 from "./routes/novel/delNovel";
import route28 from "./routes/novel/getNovel";
import route29 from "./routes/novel/updateNovel";
import route30 from "./routes/other/clearDatabase";
import route31 from "./routes/other/deleteAllData";
import route32 from "./routes/other/getCaptcha";
import route33 from "./routes/other/login";
import route34 from "./routes/other/testAI";
import route35 from "./routes/other/testImage";
import route36 from "./routes/other/testVideo";
import route37 from "./routes/outline/addOutline";
import route38 from "./routes/outline/agentsOutline";
import route39 from "./routes/outline/delOutline";
import route40 from "./routes/outline/getHistory";
import route41 from "./routes/outline/getOutline";
import route42 from "./routes/outline/getPartScript";
import route43 from "./routes/outline/getStoryline";
import route44 from "./routes/outline/setHistory";
import route45 from "./routes/outline/updateOutline";
import route46 from "./routes/outline/updateScript";
import route47 from "./routes/outline/updateStoryline";
import route48 from "./routes/performance/getMetrics";
import route49 from "./routes/project/addProject";
import route50 from "./routes/project/delProject";
import route51 from "./routes/project/getProject";
import route52 from "./routes/project/getProjectCount";
import route53 from "./routes/project/getSingleProject";
import route54 from "./routes/project/updateProject";
import route55 from "./routes/prompt/getPrompts";
import route56 from "./routes/prompt/updatePrompt";
import route57 from "./routes/script/generateScriptApi";
import route58 from "./routes/script/generateScriptSave";
import route59 from "./routes/script/getScriptApi";
import route60 from "./routes/setting/addModel";
import route61 from "./routes/setting/configurationModel";
import route62 from "./routes/setting/delModel";
import route63 from "./routes/setting/getAiModelList";
import route64 from "./routes/setting/getAiModelMap";
import route65 from "./routes/setting/getLog";
import route66 from "./routes/setting/getSetting";
import route67 from "./routes/setting/getVideoModelDetail";
import route68 from "./routes/setting/getVideoModelList";
import route69 from "./routes/setting/updateModel";
import route70 from "./routes/storyboard/batchSuperScoreImage";
import route71 from "./routes/storyboard/chatStoryboard";
import route72 from "./routes/storyboard/delStoryboard";
import route73 from "./routes/storyboard/generateShotImage";
import route74 from "./routes/storyboard/generateStoryboardApi";
import route75 from "./routes/storyboard/generateVideoPrompt";
import route76 from "./routes/storyboard/getStoryboard";
import route77 from "./routes/storyboard/keepStoryboard";
import route78 from "./routes/storyboard/saveStoryboard";
import route79 from "./routes/storyboard/uploadImage";
import route80 from "./routes/task/getTaskApi";
import route81 from "./routes/task/taskDetails";
import route82 from "./routes/user/getUser";
import route83 from "./routes/user/saveUser";
import route84 from "./routes/video/addVideo";
import route85 from "./routes/video/addVideoConfig";
import route86 from "./routes/video/deleteVideoConfig";
import route87 from "./routes/video/generatePrompt";
import route88 from "./routes/video/generateVideo";
import route89 from "./routes/video/getManufacturer";
import route90 from "./routes/video/getVideo";
import route91 from "./routes/video/getVideoConfigs";
import route92 from "./routes/video/getVideoModel";
import route93 from "./routes/video/getVideoStoryboards";
import route94 from "./routes/video/reviseVideoStoryboards";
import route95 from "./routes/video/saveVideo";
import route96 from "./routes/video/upDateVideoConfig";

export default async (app: Express) => {
  app.use("/assets/addAssets", route1);
  app.use("/assets/delAssets", route2);
  app.use("/assets/delAssetsImage", route3);
  app.use("/assets/generateAssets", route4);
  app.use("/assets/getAssets", route5);
  app.use("/assets/getImage", route6);
  app.use("/assets/getStoryboard", route7);
  app.use("/assets/polishPrompt", route8);
  app.use("/assets/saveAssets", route9);
  app.use("/assets/updateAssets", route10);
  app.use("/batch/cancelBatchTask", route11);
  app.use("/batch/createBatchTask", route12);
  app.use("/batch/getBatchTaskStatus", route13);
  app.use("/costume/addCostume", route14);
  app.use("/costume/checkConsistency", route15);
  app.use("/costume/deleteCostume", route16);
  app.use("/costume/generateCostume", route17);
  app.use("/costume/getCostumes", route18);
  app.use("/costume/updateCostume", route19);
  app.use("/format/convertFormat", route20);
  app.use("/format/detectFormat", route21);
  app.use("/format/parseFormat", route22);
  app.use("/index", route23);
  app.use("/monitoring/health", route24);
  app.use("/monitoring/metrics", route25);
  app.use("/novel/addNovel", route26);
  app.use("/novel/delNovel", route27);
  app.use("/novel/getNovel", route28);
  app.use("/novel/updateNovel", route29);
  app.use("/other/clearDatabase", route30);
  app.use("/other/deleteAllData", route31);
  app.use("/other/getCaptcha", route32);
  app.use("/other/login", route33);
  app.use("/other/testAI", route34);
  app.use("/other/testImage", route35);
  app.use("/other/testVideo", route36);
  app.use("/outline/addOutline", route37);
  app.use("/outline/agentsOutline", route38);
  app.use("/outline/delOutline", route39);
  app.use("/outline/getHistory", route40);
  app.use("/outline/getOutline", route41);
  app.use("/outline/getPartScript", route42);
  app.use("/outline/getStoryline", route43);
  app.use("/outline/setHistory", route44);
  app.use("/outline/updateOutline", route45);
  app.use("/outline/updateScript", route46);
  app.use("/outline/updateStoryline", route47);
  app.use("/performance/getMetrics", route48);
  app.use("/project/addProject", route49);
  app.use("/project/delProject", route50);
  app.use("/project/getProject", route51);
  app.use("/project/getProjectCount", route52);
  app.use("/project/getSingleProject", route53);
  app.use("/project/updateProject", route54);
  app.use("/prompt/getPrompts", route55);
  app.use("/prompt/updatePrompt", route56);
  app.use("/script/generateScriptApi", route57);
  app.use("/script/generateScriptSave", route58);
  app.use("/script/getScriptApi", route59);
  app.use("/setting/addModel", route60);
  app.use("/setting/configurationModel", route61);
  app.use("/setting/delModel", route62);
  app.use("/setting/getAiModelList", route63);
  app.use("/setting/getAiModelMap", route64);
  app.use("/setting/getLog", route65);
  app.use("/setting/getSetting", route66);
  app.use("/setting/getVideoModelDetail", route67);
  app.use("/setting/getVideoModelList", route68);
  app.use("/setting/updateModel", route69);
  app.use("/storyboard/batchSuperScoreImage", route70);
  app.use("/storyboard/chatStoryboard", route71);
  app.use("/storyboard/delStoryboard", route72);
  app.use("/storyboard/generateShotImage", route73);
  app.use("/storyboard/generateStoryboardApi", route74);
  app.use("/storyboard/generateVideoPrompt", route75);
  app.use("/storyboard/getStoryboard", route76);
  app.use("/storyboard/keepStoryboard", route77);
  app.use("/storyboard/saveStoryboard", route78);
  app.use("/storyboard/uploadImage", route79);
  app.use("/task/getTaskApi", route80);
  app.use("/task/taskDetails", route81);
  app.use("/user/getUser", route82);
  app.use("/user/saveUser", route83);
  app.use("/video/addVideo", route84);
  app.use("/video/addVideoConfig", route85);
  app.use("/video/deleteVideoConfig", route86);
  app.use("/video/generatePrompt", route87);
  app.use("/video/generateVideo", route88);
  app.use("/video/getManufacturer", route89);
  app.use("/video/getVideo", route90);
  app.use("/video/getVideoConfigs", route91);
  app.use("/video/getVideoModel", route92);
  app.use("/video/getVideoStoryboards", route93);
  app.use("/video/reviseVideoStoryboards", route94);
  app.use("/video/saveVideo", route95);
  app.use("/video/upDateVideoConfig", route96);
}
